#CONSTANTE
BACKGROUND = ' '
DEFAULT_CHAR = "@"
DEFAULT_DEPLACEMENT = 0.01
DEFAULT_GRAVITE = 0.02
DEFAULT_JUMP = 0.05
# math.pi/2 ~= 1.57
PI_SUR_DEUX = 1.57
X, Y, Z = 0, 1, 2
LIGHT_GRADIENT = ".,;la#@"
